# Generated by Django 4.2.30 on 2026-09-18 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alternatives_count', models.IntegerField(default=3, help_text='Кроме лучшего сорта. 3 — показываем лучший и ещё три.', verbose_name='Сколько альтернатив показывать')),
                ('min_score_to_show', models.IntegerField(default=1, help_text='Пары со звёздами ниже этой в подбор не попадают.', verbose_name='Минимальная оценка пары')),
                ('show_wheat_decor', models.BooleanField(default=True, help_text='Пшеница слева и справа, которая едет при прокрутке.', verbose_name='Колосья по бокам страницы')),
                ('pairing_intro', models.TextField(blank=True, default='Мы разложили сорт на вкусовые ноты и нашли блюда, которые с ними совпадают.', verbose_name='Подпись над парами')),
            ],
            options={
                'verbose_name': 'Настройки витрины',
                'verbose_name_plural': 'Настройки витрины',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='HEX вида #F5A623. Задаёт фон страницы сорта и подложку под бутылкой. Если пусто — берётся цвет темы сайта.', max_length=9, verbose_name='Цвет страницы'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Одна строка над названием на странице сорта, например «Классика пильзнера».', max_length=200, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='flavornote',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка ингредиента на прозрачном фоне: ромашка, колос, шишка хмеля, сота мёда. Показывается вокруг бутылки на странице сорта. Если пусто — берётся emoji.', max_length=500, null=True, upload_to='flavor_notes/', verbose_name='Фото вкуса'),
        ),
        migrations.CreateModel(
            name='FoodIcon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CATEGORY', 'Категория блюда'), ('COOKING', 'Способ приготовления'), ('TASTE', 'Вкус'), ('WEIGHT', 'Сытность')], max_length=20, verbose_name='Тип')),
                ('key', models.CharField(help_text='Категория: MEAT, SALAD, SOUP, ASIAN, SEAFOOD, PIZZA, STREET, SIDES, DESSERT, SNACK. Приготовление: FRIED, GRILLED, BAKED, BOILED, STEAMED, RAW, CURED, FERMENTED. Вкус: SALTY, SWEET, SOUR, BITTER, UMAMI, SPICY, MIXED. Сытность: LIGHT, MEDIUM, HEAVY.', max_length=30, verbose_name='Код')),
                ('label', models.CharField(blank=True, default='', help_text='Если пусто — берётся название с фронтенда.', max_length=100, verbose_name='Подпись')),
                ('image', models.ImageField(help_text='PNG на прозрачном фоне, примерно 400×400.', max_length=500, upload_to='food_icons/', verbose_name='Картинка')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Иллюстрация блюда',
                'verbose_name_plural': 'Иллюстрации блюд',
                'ordering': ['kind', 'sort_order', 'key'],
                'unique_together': {('kind', 'key')},
            },
        ),
    ]
