# Generated by Django 4.2.30 on 2026-09-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sitesettings_brand_accent_color_brand_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image_hd',
            field=models.ImageField(blank=True, help_text='Крупная версия для страницы сорта и большой карточки подбора. Если пусто - там показывается обычное изображение.', max_length=500, null=True, upload_to='brands/hd/', verbose_name='Фото в высоком качестве'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, help_text='Лёгкий файл для мелких мест: карточки каталога, список альтернатив, значок в подборе.', max_length=500, null=True, upload_to='brands/', verbose_name='Изображение / Бутылка'),
        ),
    ]
