# Generated by Django 4.2.30 on 2026-09-22 21:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_lead_qrcode_is_active_qrcode_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PairingReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "drink_id",
                    models.CharField(
                        max_length=80, verbose_name="Напиток (id в data/drinks.json)"
                    ),
                ),
                (
                    "dish_id",
                    models.CharField(
                        max_length=80,
                        verbose_name="Блюдо (id в data/dishes_v2.json или custom)",
                    ),
                ),
                (
                    "dish_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Название своего блюда (для custom)",
                    ),
                ),
                (
                    "dish_key",
                    models.CharField(
                        editable=False,
                        help_text="Для «одна оценка на пару» и сводок по своему блюду",
                        max_length=130,
                        verbose_name="Ключ блюда: id или custom:<название>",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка 1–5",
                    ),
                ),
                (
                    "helpful",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Подбор помог"
                    ),
                ),
                (
                    "chips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Метки (id из reviews_logic.REVIEW_CHIPS)",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="Текст (≤ 1000, телефоны и e-mail скрыты)",
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("kk", "Қазақша"),
                            ("en", "English"),
                        ],
                        default="ru",
                        max_length=5,
                        verbose_name="Язык интерфейса гостя",
                    ),
                ),
                (
                    "table_number",
                    models.IntegerField(blank=True, null=True, verbose_name="Стол"),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="В заведении был скан QR той же сессией за последние 12 ч — вес ×1.5 в сводках",
                        verbose_name="Из заведения (была сессия QR)",
                    ),
                ),
                (
                    "session_hash",
                    models.CharField(max_length=64, verbose_name="Сессия (HMAC)"),
                ),
                ("ip_hash", models.CharField(max_length=64, verbose_name="IP (HMAC)")),
                (
                    "ua_short",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Тип устройства",
                    ),
                ),
                (
                    "engine_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Версия движка",
                    ),
                ),
                (
                    "calibration_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Версия калибровки",
                    ),
                ),
                (
                    "score_shown",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Балл движка, который видел гость",
                    ),
                ),
                (
                    "ctx",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Контекст подбора (повод, предпочтения)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Опубликован"),
                            ("pending", "На проверке"),
                            ("hidden", "Скрыт модератором"),
                            ("spam", "Спам"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "heuristics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Офлайн-эвристики текста"
                    ),
                ),
                (
                    "edit_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Правок текста с ИИ-разбором"
                    ),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Решение модератора"
                    ),
                ),
                (
                    "ai_sentiment",
                    models.FloatField(
                        blank=True, null=True, verbose_name="ИИ: тональность −1..1"
                    ),
                ),
                (
                    "ai_aspects",
                    models.JSONField(
                        blank=True, default=list, verbose_name="ИИ: метки из текста"
                    ),
                ),
                (
                    "ai_summary_ru",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="ИИ: пересказ",
                    ),
                ),
                (
                    "ai_flags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="ИИ: флаги (spam, toxic, offtopic, other_dish)",
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="ИИ: модель"
                    ),
                ),
                (
                    "ai_analyzed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ИИ: когда разобран"
                    ),
                ),
                (
                    "ai_error",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="ИИ: ошибка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pairing_reviews",
                        to="api.venue",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв о паре",
                "verbose_name_plural": "Отзывы о парах",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["drink_id", "dish_id"], name="review_pair_idx"
                    ),
                    models.Index(
                        fields=["ip_hash", "updated_at"], name="review_ip_rate_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pairingreview",
            constraint=models.UniqueConstraint(
                fields=("session_hash", "drink_id", "dish_key"),
                name="review_one_per_session_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="pairingreview",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="review_rating_1_5",
            ),
        ),
    ]
