# Generated by Django 4.2.30 on 2026-09-22 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_pairing_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="PairingAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("open_drink", "Открыл карточку напитка"),
                            ("expand_why", "Раскрыл «почему»"),
                            ("order_intent", "Нажал «Заказать»"),
                            ("review", "Оставил отзыв"),
                        ],
                        max_length=16,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "list_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Список (uuid клиента)"
                    ),
                ),
                (
                    "drink_id",
                    models.CharField(
                        max_length=80, verbose_name="Напиток (id в drinks.json)"
                    ),
                ),
                (
                    "dish_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="Блюдо (id в dishes_v2 или custom)",
                    ),
                ),
                (
                    "efes",
                    models.BooleanField(
                        default=False, verbose_name="Портфель Efes (из drinks.json)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена позиции, ₸",
                    ),
                ),
                (
                    "session_hash",
                    models.CharField(max_length=64, verbose_name="Сессия (HMAC)"),
                ),
                ("ip_hash", models.CharField(max_length=64, verbose_name="IP (HMAC)")),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, verbose_name="Демо (seed_brand_demo)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Когда",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pairing_actions",
                        to="api.venue",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие гостя с подбором",
                "verbose_name_plural": "Действия гостей с подбором",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PairingImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_id", models.UUIDField(verbose_name="Список (uuid клиента)")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pair", "Подбор на сайте"),
                            ("venue_menu", "Меню заведения"),
                            ("ai", "ИИ-сомелье"),
                        ],
                        max_length=12,
                        verbose_name="Где показан",
                    ),
                ),
                (
                    "table_number",
                    models.IntegerField(blank=True, null=True, verbose_name="Стол"),
                ),
                (
                    "dish_id",
                    models.CharField(
                        max_length=80, verbose_name="Блюдо (id в dishes_v2 или custom)"
                    ),
                ),
                (
                    "tab",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=12,
                        verbose_name="Вкладка (best, beer, na …)",
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Повод"
                    ),
                ),
                (
                    "locale",
                    models.CharField(default="ru", max_length=5, verbose_name="Язык"),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        verbose_name="Место в показанном списке"
                    ),
                ),
                (
                    "honest_rank",
                    models.PositiveSmallIntegerField(
                        verbose_name="Место по баллу: 1 + сколько в списке строго выше"
                    ),
                ),
                (
                    "drink_id",
                    models.CharField(
                        max_length=80, verbose_name="Напиток (id в drinks.json)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=20, verbose_name="Категория (из drinks.json)"
                    ),
                ),
                (
                    "archetype",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="Архетип стиля (из drinks.json)",
                    ),
                ),
                (
                    "efes",
                    models.BooleanField(
                        default=False, verbose_name="Портфель Efes (из drinks.json)"
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(verbose_name="Балл движка")),
                (
                    "pool_best_other",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Лучший балл не-Efes во всём пуле кандидатов (0 — конкурентов в пуле нет, пусто — клиент не прислал)",
                    ),
                ),
                (
                    "session_hash",
                    models.CharField(max_length=64, verbose_name="Сессия (HMAC)"),
                ),
                ("ip_hash", models.CharField(max_length=64, verbose_name="IP (HMAC)")),
                (
                    "engine_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Версия движка",
                    ),
                ),
                (
                    "calibration_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Версия калибровки",
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, verbose_name="Демо (seed_brand_demo)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Когда",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pairing_impressions",
                        to="api.venue",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Показ напитка в подборе",
                "verbose_name_plural": "Показы напитков в подборе",
                "ordering": ["-created_at", "list_id", "rank"],
                "indexes": [
                    models.Index(fields=["efes", "rank"], name="impr_efes_rank_idx"),
                    models.Index(fields=["dish_id"], name="impr_dish_idx"),
                    models.Index(
                        fields=["venue", "created_at"], name="impr_venue_time_idx"
                    ),
                    models.Index(
                        fields=["is_demo", "created_at"], name="impr_demo_time_idx"
                    ),
                    models.Index(
                        fields=["session_hash", "created_at"],
                        name="impr_session_rate_idx",
                    ),
                    models.Index(
                        fields=["ip_hash", "created_at"], name="impr_ip_rate_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pairingimpression",
            constraint=models.UniqueConstraint(
                fields=("list_id", "drink_id"), name="impr_one_drink_per_list"
            ),
        ),
        migrations.AddIndex(
            model_name="pairingaction",
            index=models.Index(
                fields=["kind", "created_at"], name="action_kind_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pairingaction",
            index=models.Index(
                fields=["venue", "created_at"], name="action_venue_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pairingaction",
            index=models.Index(
                fields=["is_demo", "created_at"], name="action_demo_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pairingaction",
            index=models.Index(
                fields=["session_hash", "created_at"], name="action_session_rate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pairingaction",
            index=models.Index(
                fields=["ip_hash", "created_at"], name="action_ip_rate_idx"
            ),
        ),
        migrations.CreateModel(
            name="TrackingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=64, verbose_name="Ключ (HMAC адреса или global)"
                    ),
                ),
                ("minute", models.DateTimeField(verbose_name="Минута")),
                ("n", models.PositiveIntegerField(default=0, verbose_name="Событий")),
            ],
            options={
                "verbose_name": "Лимит трекинга (минута)",
                "verbose_name_plural": "Лимиты трекинга (минуты)",
                "indexes": [
                    models.Index(fields=["minute"], name="track_rate_minute_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="trackingrate",
            constraint=models.UniqueConstraint(
                fields=("key", "minute"), name="track_rate_key_minute"
            ),
        ),
    ]
