# Generated by Django 4.2.30 on 2026-09-23 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_change_requests_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDrink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, тг')),
                ('volume', models.CharField(blank=True, default='', help_text='Например «0,5 л» или «0,33 л».', max_length=40, verbose_name='Объём')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_drinks', to='api.brand', verbose_name='Сорт')),
            ],
            options={
                'verbose_name': 'Напиток в карте',
                'verbose_name_plural': 'Напитки в карте',
                'ordering': ['sort_order', 'brand__name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(help_text='Сквозной номер внутри заведения, с 1.', verbose_name='Номер')),
                ('table_number', models.IntegerField(help_text='0 - без стола (с собой).', verbose_name='Стол')),
                ('guest_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Имя гостя')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('ACCEPTED', 'Принят'), ('COOKING', 'Готовится'), ('SERVED', 'Подан'), ('DONE', 'Закрыт'), ('CANCELLED', 'Отменён')], default='NEW', max_length=10, verbose_name='Статус')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма, тг')),
                ('guest_token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Токен гостя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='venue',
            name='tables_count',
            field=models.PositiveIntegerField(default=20, help_text='Гость выбирает стол от 1 до этого числа при заказе.', verbose_name='Количество столов'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DISH', 'Блюдо'), ('DRINK', 'Напиток')], max_length=5, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, тг')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Пожелание')),
                ('menu_drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.menudrink', verbose_name='Напиток в карте')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.menuitem', verbose_name='Позиция меню')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.venue', verbose_name='Заведение'),
        ),
        migrations.AddField(
            model_name='menudrink',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_drinks', to='api.venue', verbose_name='Заведение'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('venue', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='menudrink',
            unique_together={('venue', 'brand')},
        ),
    ]
