# Generated by Django 4.2.30 on 2026-10-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_foodpairing_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='День')),
                ('kind', models.CharField(max_length=20, verbose_name='Тип')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Обращений')),
            ],
            options={
                'verbose_name': 'Расход ИИ за день',
                'verbose_name_plural': 'Расход ИИ по дням',
                'ordering': ['-day', 'kind'],
                'unique_together': {('day', 'kind')},
            },
        ),
    ]
