# Generated by Django 4.2.30 on 2026-10-02 00:47

from django.db import migrations, models


def keep_one_venue_per_owner(apps, schema_editor):
    """У кого больше одного заведения, тому оставляем первое по названию: иначе ограничение не встанет."""
    Venue = apps.get_model('api', 'Venue')
    seen = set()
    for venue in Venue.objects.exclude(owner__isnull=True).order_by('name', 'created_at'):
        if venue.owner_id in seen:
            Venue.objects.filter(pk=venue.pk).update(owner=None)
        else:
            seen.add(venue.owner_id)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_aiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Путь')),
                ('content', models.BinaryField(verbose_name='Содержимое')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Тип')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Загружен')),
            ],
            options={
                'verbose_name': 'Файл в базе',
                'verbose_name_plural': 'Файлы в базе',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(keep_one_venue_per_owner, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner',), name='one_venue_per_owner'),
        ),
    ]
