# Generated by Django 4.2.30 on 2026-10-02 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_storage_venue_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(1, 'Новичок'), (2, 'Исследователь'), (3, 'Знаток'), (4, 'Сомелье')], verbose_name='Ступень')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Адрес')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('summary', models.CharField(blank=True, default='', max_length=300, verbose_name='Коротко о чём')),
                ('minutes', models.PositiveSmallIntegerField(default=3, verbose_name='Минут на чтение')),
                ('blocks', models.JSONField(blank=True, default=list, help_text='Список блоков. Типы: text, facts, steps, tip, check, practice.', verbose_name='Содержимое')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['level', 'sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Сгенерирован командой seed_demo_orders для показа аналитики. В списке заказов не виден, в аналитике помечен как демо.', verbose_name='Демо-заказ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='via',
            field=models.CharField(choices=[('MENU', 'Из меню'), ('PAIRING', 'По совету пары'), ('AI', 'Из чата ИИ-сомелье')], default='MENU', max_length=10, verbose_name='Откуда добавлено'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_team',
            field=models.BooleanField(default=False, help_text='Включайте, когда в разделе «Команда» записаны настоящие люди: стартовые записи в нём условные.', verbose_name='Блок команды в Академии'),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Описание')),
                ('kind', models.CharField(choices=[('FOOD', 'Угощение от кухни'), ('SOFT', 'Безалкогольный напиток'), ('MERCH', 'Сувенир'), ('EVENT', 'Событие')], default='FOOD', max_length=10, verbose_name='Тип')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена в баллах')),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Пусто - без ограничения.', null=True, verbose_name='Осталось штук')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='api.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ['cost', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Название на момент обмена')),
                ('cost', models.PositiveIntegerField(verbose_name='Списано баллов')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Код')),
                ('status', models.CharField(choices=[('ISSUED', 'Код выдан'), ('USED', 'Получена'), ('CANCELLED', 'Отменена')], default='ISSUED', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Выдана')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='api.reward', verbose_name='Награда')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions_given', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='api.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Обмен баллов',
                'verbose_name_plural': 'Обмены баллов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PairingFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device', models.CharField(blank=True, default='', max_length=64, verbose_name='Устройство')),
                ('liked', models.BooleanField(verbose_name='Подошло')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.foodpairing', verbose_name='Пара')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairing_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_feedback', to='api.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Оценка пары',
                'verbose_name_plural': 'Оценки пар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пройденный урок',
                'verbose_name_plural': 'Пройденные уроки',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка 1-5')),
                ('comment', models.CharField(blank=True, default='', max_length=280, verbose_name='Заметка')),
                ('matched', models.PositiveSmallIntegerField(default=0, help_text='Сколько выбранных нот есть в пирамиде сомелье на момент отметки.', verbose_name='Совпало нот с пирамидой')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tastings', to='api.brand', verbose_name='Сорт')),
                ('notes', models.ManyToManyField(blank=True, related_name='tastings', to='api.flavornote', verbose_name='Что услышал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tastings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tastings', to='api.venue', verbose_name='Где пробовал')),
            ],
            options={
                'verbose_name': 'Отметка в паспорте вкуса',
                'verbose_name_plural': 'Паспорт вкуса: отметки',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'brand')},
            },
        ),
        migrations.AddConstraint(
            model_name='pairingfeedback',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('pairing', 'user'), name='one_feedback_per_user'),
        ),
        migrations.AddConstraint(
            model_name='pairingfeedback',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('device', ''), _negated=True)), fields=('pairing', 'device'), name='one_feedback_per_device'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
    ]
