# Generated by Django 4.2.30 on 2026-09-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_menu_drinks_orders"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnginePairingWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overrides",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Переопределения весов"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=0, verbose_name="Версия"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Кто менял"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Веса движка подбора",
                "verbose_name_plural": "Веса движка подбора",
            },
        ),
    ]
