# Generated by Django 4.2.30 on 2026-09-25 23:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_enginepairingweights"),
    ]

    operations = [
        migrations.CreateModel(
            name="PairingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=36,
                        verbose_name="Сессия гостя",
                    ),
                ),
                (
                    "dish_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Блюдо (ссылка)",
                    ),
                ),
                (
                    "drink_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Напиток (ссылка)",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка пары",
                "verbose_name_plural": "Оценки пар",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PilotEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=36,
                        verbose_name="Сессия гостя",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SCAN", "Скан QR"),
                            ("MENU_OPEN", "Открыл меню"),
                            ("PAIR_OPEN", "Открыл подбор"),
                            ("PAIR_ADD", "Добавил напиток из подбора"),
                            ("ORDER", "Заказ"),
                            ("FEEDBACK", "Оценка пары"),
                            ("AGE_OK", "Подтвердил возраст"),
                            ("AI_ASK", "Вопрос ИИ-сомелье"),
                            ("AI_ADD", "Добавил из чата ИИ"),
                            ("CATALOG_OPEN", "Открыл каталог"),
                            ("PAIRING_V2", "Подбор на сайте"),
                        ],
                        max_length=24,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "table_number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Стол"
                    ),
                ),
                (
                    "dish_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="id позиции меню, блюда движка или название, если позиции меню нет.",
                        max_length=64,
                        verbose_name="Блюдо (ссылка)",
                    ),
                ),
                (
                    "drink_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="id напитка в карте, напитка движка или название.",
                        max_length=64,
                        verbose_name="Напиток (ссылка)",
                    ),
                ),
                (
                    "rank",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Место в подборе"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="Источник"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Подробности"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие пилота",
                "verbose_name_plural": "События пилота",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="menudrink",
            options={
                "ordering": ["sort_order", "brand__name", "name"],
                "verbose_name": "Напиток в карте",
                "verbose_name_plural": "Напитки в карте",
            },
        ),
        migrations.AddField(
            model_name="menudrink",
            name="engine_drink_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="id из data/engine/drinks.json, например efes-0-0. Можно не заполнять, если выбран сорт.",
                max_length=64,
                verbose_name="Напиток движка подбора",
            ),
        ),
        migrations.AddField(
            model_name="menudrink",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Показывается, когда сорт не выбран.",
                max_length=120,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="age_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Гость подтвердил возраст"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="session",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Анонимный id браузера (ft_sid), связывает заказ с событиями пилота.",
                max_length=36,
                verbose_name="Сессия гостя",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="paired_menu_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.menuitem",
                verbose_name="Подобрано к блюду",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="rec_rank",
            field=models.SmallIntegerField(
                blank=True,
                help_text="1 - лучший вариант, 2 и дальше - альтернативы.",
                null=True,
                verbose_name="Место в подборе",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="source",
            field=models.CharField(
                choices=[("MENU", "Меню"), ("PAIRING", "Подбор"), ("AI", "ИИ-сомелье")],
                default="MENU",
                max_length=16,
                verbose_name="Откуда добавлено",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="accepts_orders",
            field=models.BooleanField(
                default=True,
                help_text="Если выключено, меню и подбор работают, а заказ гость показывает официанту.",
                verbose_name="Принимает заказы через приложение",
            ),
        ),
        migrations.AlterField(
            model_name="menudrink",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_drinks",
                to="api.brand",
                verbose_name="Сорт",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="api.venue",
                verbose_name="Заведение",
            ),
        ),
        migrations.AddConstraint(
            model_name="menudrink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("engine_drink_id", ""), _negated=True),
                fields=("venue", "engine_drink_id"),
                name="menudrink_venue_engine_drink_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="menudrink",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("brand__isnull", False),
                    models.Q(("engine_drink_id", ""), _negated=True),
                    _connector="OR",
                ),
                name="menudrink_brand_or_engine_drink",
            ),
        ),
        migrations.AddField(
            model_name="pilotevent",
            name="menu_drink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.menudrink",
                verbose_name="Напиток в карте",
            ),
        ),
        migrations.AddField(
            model_name="pilotevent",
            name="menu_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.menuitem",
                verbose_name="Блюдо меню",
            ),
        ),
        migrations.AddField(
            model_name="pilotevent",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pilot_events",
                to="api.venue",
                verbose_name="Заведение",
            ),
        ),
        migrations.AddField(
            model_name="pairingfeedback",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pairing_feedback",
                to="api.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="pairingfeedback",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pairing_feedback",
                to="api.venue",
                verbose_name="Заведение",
            ),
        ),
        migrations.AddIndex(
            model_name="pilotevent",
            index=models.Index(
                fields=["venue", "kind", "created_at"],
                name="pilotevent_venue_kind_time",
            ),
        ),
    ]
