# Generated by Django 4.2.30 on 2026-10-01 21:09

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_pilot'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(1, 'Новичок'), (2, 'Исследователь'), (3, 'Знаток'), (4, 'Сомелье')], verbose_name='Ступень')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('options', models.JSONField(default=list, help_text='Список строк, от 2 до 6 вариантов.', verbose_name='Варианты ответа')),
                ('correct_index', models.IntegerField(default=0, help_text='Считается с нуля: 0 - первый вариант.', verbose_name='Номер верного ответа')),
                ('explanation', models.TextField(blank=True, default='', help_text='Показывается после ответа: почему верно именно так.', verbose_name='Пояснение')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в тесте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ['level', 'sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.JSONField(blank=True, default=api.models.default_taste, help_text='Шкалы 0-10: body, bitterness, freshness, sweetness, roast, strength. Пустая шкала значит "не важно".', verbose_name='Вкусовые предпочтения')),
                ('cuisines', models.JSONField(blank=True, default=list, help_text='Коды кухонь, как у блюд: KZ, ITALIAN, ...', verbose_name='Любимые кухни')),
                ('sommelier_level', models.IntegerField(default=0, verbose_name='Пройдено ступеней Школы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('favorite_brands', models.ManyToManyField(blank=True, related_name='fans', to='api.brand', verbose_name='Любимые сорта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предпочтения пользователя',
                'verbose_name_plural': 'Предпочтения пользователей',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(1, 'Новичок'), (2, 'Исследователь'), (3, 'Знаток'), (4, 'Сомелье')], verbose_name='Ступень')),
                ('correct', models.IntegerField(verbose_name='Верных ответов')),
                ('total', models.IntegerField(verbose_name='Всего вопросов')),
                ('passed', models.BooleanField(verbose_name='Сдано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки теста',
                'ordering': ['-created_at'],
            },
        ),
    ]
