# Generated by Django 4.2.30 on 2026-10-02 00:47

from django.db import migrations, models


def keep_one_venue_per_owner(apps, schema_editor):
    """У кого больше одного заведения, тому оставляем первое по названию: иначе ограничение не встанет."""
    Venue = apps.get_model('api', 'Venue')
    seen = set()
    for venue in Venue.objects.exclude(owner__isnull=True).order_by('name', 'created_at'):
        if venue.owner_id in seen:
            Venue.objects.filter(pk=venue.pk).update(owner=None)
        else:
            seen.add(venue.owner_id)


# Таблица StoredFile из версии 11 не создаётся: загруженные фото хранит приложение media_db (как на проде).


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_aiusage'),
    ]

    operations = [
        migrations.RunPython(keep_one_venue_per_owner, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner',), name='one_venue_per_owner'),
        ),
    ]
