# Generated by Django 4.2.30 on 2026-09-23 19:07, затем дополнено вручную:
# slug добавляется без индекса и unique, заполняется для существующих записей и только потом становится уникальным.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid

from api.slugs import unique_slug


def fill_venue_slugs(apps, schema_editor):
    Venue = apps.get_model('api', 'Venue')
    taken = set(Venue.objects.exclude(slug='').values_list('slug', flat=True))
    for venue in Venue.objects.filter(slug='').order_by('name'):
        slug = unique_slug(venue.name, lambda candidate: candidate in taken)
        taken.add(slug)
        Venue.objects.filter(pk=venue.pk).update(slug=slug)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_brand_image_hd_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, default='Алматы', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='venue',
            name='cover',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, db_index=False, default='', help_text='Часть ссылки на электронное меню. Если пусто - строится из названия.', max_length=120, verbose_name='Адрес меню (slug)'),
            preserve_default=False,
        ),
        migrations.RunPython(fill_venue_slugs, noop),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, help_text='Часть ссылки на электронное меню. Если пусто - строится из названия.', max_length=120, unique=True, verbose_name='Адрес меню (slug)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Часы работы'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, тг')),
                ('section', models.CharField(default='Основное', max_length=80, verbose_name='Раздел меню')),
                ('portion', models.CharField(blank=True, default='', help_text='Например «350 г» или «2 шт».', max_length=60, verbose_name='Порция')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('chef_note', models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий повара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.dish', verbose_name='Блюдо')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.venue', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Позиция меню',
                'verbose_name_plural': 'Позиции меню',
                'ordering': ['section', 'sort_order', 'dish__name'],
                'unique_together': {('venue', 'dish')},
            },
        ),
    ]
