# Generated by Django 4.2.30 on 2026-09-23 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auth_roles_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загруженный файл показывается вместо ссылки. PNG, JPG или WebP до 5 МБ.', max_length=500, null=True, upload_to='dishes/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='venue',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Загруженный файл показывается вместо ссылки.', max_length=500, null=True, upload_to='venues/', verbose_name='Логотип (файл)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Изображение (ссылка)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='logo',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Логотип (ссылка)'),
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('NOTE_UPSERT', 'Нота пирамиды'), ('NOTE_DELETE', 'Удалить ноту'), ('SERVING', 'Подача')], max_length=20, verbose_name='Тип')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='NOTE_UPSERT: flavor_note_id, layer, intensity, sommelier_note. NOTE_DELETE: flavor_note_id. SERVING: serving_temp_min, serving_temp_max, glass_type, seasonality.', verbose_name='Данные')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Пояснение автора')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('APPROVED', 'Принято'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='Комментарий модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='api.brand', verbose_name='Бренд')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Запрос на изменение',
                'verbose_name_plural': 'Запросы на изменение',
                'ordering': ['-created_at'],
            },
        ),
    ]
